---
title: "conditionals_loops"
author: "BJ"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

##Task 1

```{r}
#create an object 
pm2_5 <- 48

#write an if- else if- else statement about air quality

if(pm2_5 < 100) {
  print("low to moderate risk") 
} else if (pm2_5 >= 100 & pm2_5 < 150) {
  print("unhealthy for sensitive groups")
} else
  print("health risk present")
```

## Task 2

```{r}
#strings, storing strings to return statements
library(stringr)

species <- "blue whale" 

if(str_detect(species, "whale")) {
  print("you found a whale!")
}
```

## Task 3

```{r}
base_burrito <- 6.50
main_ingredient <- "chicken"

if(main_ingredient == "veggie"){
  print(base_burrito)
} else if (main_ingredient == "chicken"){
  print(base_burrito + 3)
} else if (main_ingredient == "steak"){
  print(base_burrito = 3.25)
}
```

## Task 4

```{r}
##percentage of fish in tank

species <- c("goldfish", "tetras", "guppies", "mollies")

fish <- c(8, 10, 12, 23)

for (i in seq_along(fish)) {
  prop_fish <- fish[i] / sum(fish)
  print(paste(species[i], prop_fish))
}
```

##Task 5

```{r}

for (i in seq_along(month.name)) {
  print(paste(month.name[i],"is month", i))
}
```

