---
title: "EOD part 2"
author: "BJ"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(here)
library(janitor)
```


```{r}
#read a file in, and change the periods to NAs, and change it all to snake case
toolik_biochem <- read.csv(here::here("data", "2011_Kling_Akchem.csv"), na.strings = c(".", "NA")) |> janitor::clean_names()

inlet_biochem <- toolik_biochem |> filter(site == "Toolik Inlet" | site == "Toolik inlet") |> dplyr::select(p_h, doc_u_m, tdn_u_m)

#finding means

mean_inlet <- vector(mode = "numeric", length = ncol(inlet_biochem))

for (i in 1:ncol(inlet_biochem)) {
  inlet_val <- mean(inlet_biochem [[i]], na.rm = TRUE) 
  mean_inlet[[i]] <- inlet_val
}
 mean_inlet
```

```{r}
library(purrr)

map(.x = inlet_biochem, .f = mean)
```

```{r}
apply(X = inlet_biochem, MARGIN = 2, FUN = mean, na.rm = TRUE)
```

```{r}
mean_inlet <- inlet_biochem |>
  summarise(across(where(is.numeric), mean, na.rm = TRUE))
            
```

